/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type AreaReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "area";
};

export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  excerpt?: string;
  body: RichText;
  mainImage?: EditorialImage;
  authorName?: string;
  publishedAt?: string;
  areas?: Array<
    {
      _key: string;
    } & AreaReference
  >;
  seo?: Seo;
  isDemo?: boolean;
  seedKey?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type EditorialImage = {
  _type: "editorialImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt: string;
  caption?: string;
  credit?: string;
};

export type RichText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & EditorialImage)
>;

export type Video = {
  _id: string;
  _type: "video";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  summary?: string;
  youtubeUrl?: string;
  thumbnail?: EditorialImage;
  publishedAt?: string;
  transcript?: RichText;
  areas?: Array<
    {
      _key: string;
    } & AreaReference
  >;
  seo?: Seo;
  isDemo?: boolean;
  seedKey?: string;
};

export type VideoReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "video";
};

export type Area = {
  _id: string;
  _type: "area";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  summary: string;
  description?: RichText;
  mainImage?: EditorialImage;
  gallery?: Array<
    {
      _key: string;
    } & EditorialImage
  >;
  highlights?: Array<string>;
  housingTypes?: Array<string>;
  location?: Geopoint;
  sortOrder?: number;
  relatedVideos?: Array<
    {
      _key: string;
    } & VideoReference
  >;
  contactAction?: Link;
  seo?: Seo;
  isDemo?: boolean;
  seedKey?: string;
};

export type Link = {
  _type: "link";
  label: string;
  href: string;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type ArticleReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "article";
};

export type Homepage = {
  _id: string;
  _type: "homepage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  heroTitle: string;
  heroSubtitle?: string;
  heroDescription?: string;
  heroImage?: EditorialImage;
  heroActions?: Array<
    {
      _key: string;
    } & Link
  >;
  featuredAreas?: Array<
    {
      _key: string;
    } & AreaReference
  >;
  featuredVideos?: Array<
    {
      _key: string;
    } & VideoReference
  >;
  featuredArticles?: Array<
    {
      _key: string;
    } & ArticleReference
  >;
  contactHeading?: string;
  contactAction?: Link;
  seo?: Seo;
  isDemo?: boolean;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  tagline?: string;
  agentName?: string;
  logo?: EditorialImage;
  phone?: string;
  email?: string;
  whatsappUrl?: string;
  siteUrl?: string;
  navigation?: Array<
    {
      _key: string;
    } & Link
  >;
  socialLinks?: Array<
    {
      _key: string;
    } & Link
  >;
  footerText?: string;
  seo?: Seo;
  isDemo?: boolean;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  image?: EditorialImage;
  canonicalUrl?: string;
  noIndex?: boolean;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type AllSanitySchemaTypes =
  | AreaReference
  | Article
  | SanityImageAssetReference
  | EditorialImage
  | RichText
  | Video
  | VideoReference
  | Area
  | Link
  | Geopoint
  | Slug
  | ArticleReference
  | Homepage
  | SiteSettings
  | Seo
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset;

// Source: lib/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_id == "siteSettings" && ($includeDemo == true || isDemo != true)][0]{_id,title,tagline,agentName,phone,email,whatsappUrl,siteUrl,logo {alt, caption, credit, crop, hotspot, asset->{_id, url, metadata{lqip, dimensions}}},navigation[]{_key,label,href},socialLinks[]{_key,label,href},footerText,isDemo,"seo": {"title": coalesce(seo.title, title), "description": coalesce(seo.description, summary, excerpt, heroDescription, ""), "noIndex": seo.noIndex == true || isDemo == true, "canonicalUrl": seo.canonicalUrl, "image": seo.image {alt, caption, credit, crop, hotspot, asset->{_id, url, metadata{lqip, dimensions}}}}}
export type SITE_SETTINGS_QUERY_RESULT =
  | {
      _id: string;
      title: string;
      tagline: null;
      agentName: null;
      phone: null;
      email: null;
      whatsappUrl: null;
      siteUrl: null;
      logo: null;
      navigation: null;
      socialLinks: null;
      footerText: null;
      isDemo: boolean | null;
      seo: {
        title: string;
        description: string;
        noIndex: boolean | false;
        canonicalUrl: string | null;
        image: {
          alt: string;
          caption: string | null;
          credit: string | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
          asset: {
            _id: string;
            url: string;
            metadata: {
              lqip: string | null;
              dimensions: SanityImageDimensions | null;
            } | null;
          } | null;
        } | null;
      };
    }
  | {
      _id: string;
      title: string;
      tagline: null;
      agentName: null;
      phone: null;
      email: null;
      whatsappUrl: null;
      siteUrl: null;
      logo: null;
      navigation: null;
      socialLinks: null;
      footerText: null;
      isDemo: boolean | null;
      seo: {
        title: string;
        description: string | "";
        noIndex: boolean | false;
        canonicalUrl: string | null;
        image: {
          alt: string;
          caption: string | null;
          credit: string | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
          asset: {
            _id: string;
            url: string;
            metadata: {
              lqip: string | null;
              dimensions: SanityImageDimensions | null;
            } | null;
          } | null;
        } | null;
      };
    }
  | {
      _id: string;
      title: string;
      tagline: string | null;
      agentName: string | null;
      phone: string | null;
      email: string | null;
      whatsappUrl: string | null;
      siteUrl: string | null;
      logo: {
        alt: string;
        caption: string | null;
        credit: string | null;
        crop: SanityImageCrop | null;
        hotspot: SanityImageHotspot | null;
        asset: {
          _id: string;
          url: string;
          metadata: {
            lqip: string | null;
            dimensions: SanityImageDimensions | null;
          } | null;
        } | null;
      } | null;
      navigation: Array<{
        _key: string;
        label: string;
        href: string;
      }> | null;
      socialLinks: Array<{
        _key: string;
        label: string;
        href: string;
      }> | null;
      footerText: string | null;
      isDemo: boolean | null;
      seo: {
        title: string;
        description: string | "";
        noIndex: boolean | false;
        canonicalUrl: string | null;
        image: {
          alt: string;
          caption: string | null;
          credit: string | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
          asset: {
            _id: string;
            url: string;
            metadata: {
              lqip: string | null;
              dimensions: SanityImageDimensions | null;
            } | null;
          } | null;
        } | null;
      };
    }
  | {
      _id: "siteSettings";
      title: string | null;
      tagline: null;
      agentName: null;
      phone: null;
      email: null;
      whatsappUrl: null;
      siteUrl: null;
      logo: null;
      navigation: null;
      socialLinks: null;
      footerText: null;
      isDemo: null;
      seo: {
        title: string | null;
        description: "";
        noIndex: false;
        canonicalUrl: null;
        image: null;
      };
    }
  | null;

// Source: lib/queries.ts
// Variable: HOMEPAGE_QUERY
// Query: *[_id == "homepage" && ($includeDemo == true || isDemo != true)][0]{_id,title,heroTitle,heroSubtitle,heroDescription,heroImage {alt, caption, credit, crop, hotspot, asset->{_id, url, metadata{lqip, dimensions}}},heroActions[]{_key,label,href},featuredAreas[]{_key,"area": @-> {_id,title,"slug":slug.current,summary,isDemo,mainImage {alt, caption, credit, crop, hotspot, asset->{_id, url, metadata{lqip, dimensions}}}}}[defined(area) && ($includeDemo == true || area.isDemo != true)],featuredVideos[]{_key,"video": @->{_id,title,"slug":slug.current,youtubeUrl,isDemo,thumbnail {alt, caption, credit, crop, hotspot, asset->{_id, url, metadata{lqip, dimensions}}}}}[defined(video) && ($includeDemo == true || video.isDemo != true)],featuredArticles[]{_key,"article": @->{_id,title,"slug":slug.current,excerpt,isDemo}}[defined(article) && ($includeDemo == true || article.isDemo != true)],contactHeading,contactAction{label,href},isDemo,"seo": {"title": coalesce(seo.title, title), "description": coalesce(seo.description, summary, excerpt, heroDescription, ""), "noIndex": seo.noIndex == true || isDemo == true, "canonicalUrl": seo.canonicalUrl, "image": seo.image {alt, caption, credit, crop, hotspot, asset->{_id, url, metadata{lqip, dimensions}}}}}
export type HOMEPAGE_QUERY_RESULT =
  | {
      _id: "homepage";
      title: string | null;
      heroTitle: null;
      heroSubtitle: null;
      heroDescription: null;
      heroImage: null;
      heroActions: null;
      featuredAreas: null;
      featuredVideos: null;
      featuredArticles: null;
      contactHeading: null;
      contactAction: null;
      isDemo: null;
      seo: {
        title: string | null;
        description: "";
        noIndex: false;
        canonicalUrl: null;
        image: null;
      };
    }
  | {
      _id: string;
      title: string;
      heroTitle: null;
      heroSubtitle: null;
      heroDescription: null;
      heroImage: null;
      heroActions: null;
      featuredAreas: null;
      featuredVideos: null;
      featuredArticles: null;
      contactHeading: null;
      contactAction: null;
      isDemo: boolean | null;
      seo: {
        title: string;
        description: string | "";
        noIndex: boolean | false;
        canonicalUrl: string | null;
        image: {
          alt: string;
          caption: string | null;
          credit: string | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
          asset: {
            _id: string;
            url: string;
            metadata: {
              lqip: string | null;
              dimensions: SanityImageDimensions | null;
            } | null;
          } | null;
        } | null;
      };
    }
  | {
      _id: string;
      title: string;
      heroTitle: null;
      heroSubtitle: null;
      heroDescription: null;
      heroImage: null;
      heroActions: null;
      featuredAreas: null;
      featuredVideos: null;
      featuredArticles: null;
      contactHeading: null;
      contactAction: null;
      isDemo: boolean | null;
      seo: {
        title: string;
        description: string | "";
        noIndex: boolean | false;
        canonicalUrl: string | null;
        image: {
          alt: string;
          caption: string | null;
          credit: string | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
          asset: {
            _id: string;
            url: string;
            metadata: {
              lqip: string | null;
              dimensions: SanityImageDimensions | null;
            } | null;
          } | null;
        } | null;
      };
    }
  | {
      _id: string;
      title: string;
      heroTitle: null;
      heroSubtitle: null;
      heroDescription: null;
      heroImage: null;
      heroActions: null;
      featuredAreas: null;
      featuredVideos: null;
      featuredArticles: null;
      contactHeading: null;
      contactAction: {
        label: string;
        href: string;
      } | null;
      isDemo: boolean | null;
      seo: {
        title: string;
        description: string;
        noIndex: boolean | false;
        canonicalUrl: string | null;
        image: {
          alt: string;
          caption: string | null;
          credit: string | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
          asset: {
            _id: string;
            url: string;
            metadata: {
              lqip: string | null;
              dimensions: SanityImageDimensions | null;
            } | null;
          } | null;
        } | null;
      };
    }
  | {
      _id: string;
      title: string;
      heroTitle: string;
      heroSubtitle: string | null;
      heroDescription: string | null;
      heroImage: {
        alt: string;
        caption: string | null;
        credit: string | null;
        crop: SanityImageCrop | null;
        hotspot: SanityImageHotspot | null;
        asset: {
          _id: string;
          url: string;
          metadata: {
            lqip: string | null;
            dimensions: SanityImageDimensions | null;
          } | null;
        } | null;
      } | null;
      heroActions: Array<{
        _key: string;
        label: string;
        href: string;
      }> | null;
      featuredAreas: Array<{
        _key: string;
        area: {
          _id: string;
          title: string;
          slug: string;
          summary: string;
          isDemo: boolean | null;
          mainImage: {
            alt: string;
            caption: string | null;
            credit: string | null;
            crop: SanityImageCrop | null;
            hotspot: SanityImageHotspot | null;
            asset: {
              _id: string;
              url: string;
              metadata: {
                lqip: string | null;
                dimensions: SanityImageDimensions | null;
              } | null;
            } | null;
          } | null;
        };
      }> | null;
      featuredVideos: Array<{
        _key: string;
        video: {
          _id: string;
          title: string;
          slug: string;
          youtubeUrl: string | null;
          isDemo: boolean | null;
          thumbnail: {
            alt: string;
            caption: string | null;
            credit: string | null;
            crop: SanityImageCrop | null;
            hotspot: SanityImageHotspot | null;
            asset: {
              _id: string;
              url: string;
              metadata: {
                lqip: string | null;
                dimensions: SanityImageDimensions | null;
              } | null;
            } | null;
          } | null;
        };
      }> | null;
      featuredArticles: Array<{
        _key: string;
        article: {
          _id: string;
          title: string;
          slug: string;
          excerpt: string | null;
          isDemo: boolean | null;
        };
      }> | null;
      contactHeading: string | null;
      contactAction: {
        label: string;
        href: string;
      } | null;
      isDemo: boolean | null;
      seo: {
        title: string;
        description: string | "";
        noIndex: boolean | false;
        canonicalUrl: string | null;
        image: {
          alt: string;
          caption: string | null;
          credit: string | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
          asset: {
            _id: string;
            url: string;
            metadata: {
              lqip: string | null;
              dimensions: SanityImageDimensions | null;
            } | null;
          } | null;
        } | null;
      };
    }
  | null;

// Source: lib/queries.ts
// Variable: AREAS_QUERY
// Query: *[_type == "area" && defined(slug.current) && ($includeDemo == true || isDemo != true)] | order(sortOrder asc, title asc)[0...100]{_id,title,"slug":slug.current,summary,mainImage {alt, caption, credit, crop, hotspot, asset->{_id, url, metadata{lqip, dimensions}}},housingTypes,highlights,isDemo,"seo": {"title": coalesce(seo.title, title), "description": coalesce(seo.description, summary, excerpt, heroDescription, ""), "noIndex": seo.noIndex == true || isDemo == true, "canonicalUrl": seo.canonicalUrl, "image": seo.image {alt, caption, credit, crop, hotspot, asset->{_id, url, metadata{lqip, dimensions}}}}}
export type AREAS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  summary: string;
  mainImage: {
    alt: string;
    caption: string | null;
    credit: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
  } | null;
  housingTypes: Array<string> | null;
  highlights: Array<string> | null;
  isDemo: boolean | null;
  seo: {
    title: string;
    description: string;
    noIndex: boolean | false;
    canonicalUrl: string | null;
    image: {
      alt: string;
      caption: string | null;
      credit: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
    } | null;
  };
}>;

// Source: lib/queries.ts
// Variable: AREA_QUERY
// Query: *[_type == "area" && slug.current == $slug && ($includeDemo == true || isDemo != true)][0]{_id,title,"slug":slug.current,summary,description[]{...,_type == "editorialImage" => {alt, caption, credit, crop, hotspot, asset->{_id, url, metadata{lqip, dimensions}}}},mainImage {alt, caption, credit, crop, hotspot, asset->{_id, url, metadata{lqip, dimensions}}},gallery[]{_key,...,asset->{_id,url,metadata{lqip,dimensions}}},housingTypes,highlights,location,contactAction{label,href},relatedVideos[]{_key,"video": @->{_id,title,youtubeUrl,isDemo}}[defined(video) && ($includeDemo == true || video.isDemo != true)],isDemo,"seo": {"title": coalesce(seo.title, title), "description": coalesce(seo.description, summary, excerpt, heroDescription, ""), "noIndex": seo.noIndex == true || isDemo == true, "canonicalUrl": seo.canonicalUrl, "image": seo.image {alt, caption, credit, crop, hotspot, asset->{_id, url, metadata{lqip, dimensions}}}}}
export type AREA_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  summary: string;
  description: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "editorialImage";
        asset: {
          _id: string;
          url: string;
          metadata: {
            lqip: string | null;
            dimensions: SanityImageDimensions | null;
          } | null;
        } | null;
        media?: unknown;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        alt: string;
        caption: string | null;
        credit: string | null;
      }
  > | null;
  mainImage: {
    alt: string;
    caption: string | null;
    credit: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
  } | null;
  gallery: Array<{
    _key: string;
    _type: "editorialImage";
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    caption?: string;
    credit?: string;
  }> | null;
  housingTypes: Array<string> | null;
  highlights: Array<string> | null;
  location: Geopoint | null;
  contactAction: {
    label: string;
    href: string;
  } | null;
  relatedVideos: Array<{
    _key: string;
    video: {
      _id: string;
      title: string;
      youtubeUrl: string | null;
      isDemo: boolean | null;
    };
  }> | null;
  isDemo: boolean | null;
  seo: {
    title: string;
    description: string;
    noIndex: boolean | false;
    canonicalUrl: string | null;
    image: {
      alt: string;
      caption: string | null;
      credit: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
    } | null;
  };
} | null;

// Source: lib/queries.ts
// Variable: VIDEOS_QUERY
// Query: *[_type == "video" && ($includeDemo == true || isDemo != true)] | order(publishedAt desc, _id asc)[0...100]{_id,title,"slug":slug.current,summary,youtubeUrl,thumbnail {alt, caption, credit, crop, hotspot, asset->{_id, url, metadata{lqip, dimensions}}},publishedAt,areas[]{_key,"area": @->{_id,title,"slug":slug.current,isDemo}}[defined(area) && ($includeDemo == true || area.isDemo != true)],isDemo,"seo": {"title": coalesce(seo.title, title), "description": coalesce(seo.description, summary, excerpt, heroDescription, ""), "noIndex": seo.noIndex == true || isDemo == true, "canonicalUrl": seo.canonicalUrl, "image": seo.image {alt, caption, credit, crop, hotspot, asset->{_id, url, metadata{lqip, dimensions}}}}}
export type VIDEOS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  summary: string | null;
  youtubeUrl: string | null;
  thumbnail: {
    alt: string;
    caption: string | null;
    credit: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
  } | null;
  publishedAt: string | null;
  areas: Array<{
    _key: string;
    area: {
      _id: string;
      title: string;
      slug: string;
      isDemo: boolean | null;
    };
  }> | null;
  isDemo: boolean | null;
  seo: {
    title: string;
    description: string | "";
    noIndex: boolean | false;
    canonicalUrl: string | null;
    image: {
      alt: string;
      caption: string | null;
      credit: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
    } | null;
  };
}>;

// Source: lib/queries.ts
// Variable: ARTICLES_QUERY
// Query: *[_type == "article" && ($includeDemo == true || isDemo != true)] | order(publishedAt desc, _id asc)[0...100]{_id,title,"slug":slug.current,excerpt,publishedAt,mainImage {alt, caption, credit, crop, hotspot, asset->{_id, url, metadata{lqip, dimensions}}},isDemo,"seo": {"title": coalesce(seo.title, title), "description": coalesce(seo.description, summary, excerpt, heroDescription, ""), "noIndex": seo.noIndex == true || isDemo == true, "canonicalUrl": seo.canonicalUrl, "image": seo.image {alt, caption, credit, crop, hotspot, asset->{_id, url, metadata{lqip, dimensions}}}}}
export type ARTICLES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  excerpt: string | null;
  publishedAt: string | null;
  mainImage: {
    alt: string;
    caption: string | null;
    credit: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
  } | null;
  isDemo: boolean | null;
  seo: {
    title: string;
    description: string | "";
    noIndex: boolean | false;
    canonicalUrl: string | null;
    image: {
      alt: string;
      caption: string | null;
      credit: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
    } | null;
  };
}>;

// Source: lib/queries.ts
// Variable: ARTICLE_QUERY
// Query: *[_type == "article" && slug.current == $slug && ($includeDemo == true || isDemo != true)][0]{_id,title,"slug":slug.current,excerpt,body[]{...,_type == "editorialImage" => {alt, caption, credit, crop, hotspot, asset->{_id, url, metadata{lqip, dimensions}}}},authorName,publishedAt,mainImage {alt, caption, credit, crop, hotspot, asset->{_id, url, metadata{lqip, dimensions}}},areas[]{_key,"area": @->{_id,title,"slug":slug.current,isDemo}}[defined(area) && ($includeDemo == true || area.isDemo != true)],isDemo,"seo": {"title": coalesce(seo.title, title), "description": coalesce(seo.description, summary, excerpt, heroDescription, ""), "noIndex": seo.noIndex == true || isDemo == true, "canonicalUrl": seo.canonicalUrl, "image": seo.image {alt, caption, credit, crop, hotspot, asset->{_id, url, metadata{lqip, dimensions}}}}}
export type ARTICLE_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  excerpt: string | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "editorialImage";
        asset: {
          _id: string;
          url: string;
          metadata: {
            lqip: string | null;
            dimensions: SanityImageDimensions | null;
          } | null;
        } | null;
        media?: unknown;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        alt: string;
        caption: string | null;
        credit: string | null;
      }
  >;
  authorName: string | null;
  publishedAt: string | null;
  mainImage: {
    alt: string;
    caption: string | null;
    credit: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
  } | null;
  areas: Array<{
    _key: string;
    area: {
      _id: string;
      title: string;
      slug: string;
      isDemo: boolean | null;
    };
  }> | null;
  isDemo: boolean | null;
  seo: {
    title: string;
    description: string | "";
    noIndex: boolean | false;
    canonicalUrl: string | null;
    image: {
      alt: string;
      caption: string | null;
      credit: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
    } | null;
  };
} | null;

// Query TypeMap
declare global {
  interface SanityQueries {
    '*[_id == "siteSettings" && ($includeDemo == true || isDemo != true)][0]{_id,title,tagline,agentName,phone,email,whatsappUrl,siteUrl,logo {alt, caption, credit, crop, hotspot, asset->{_id, url, metadata{lqip, dimensions}}},navigation[]{_key,label,href},socialLinks[]{_key,label,href},footerText,isDemo,"seo": {"title": coalesce(seo.title, title), "description": coalesce(seo.description, summary, excerpt, heroDescription, ""), "noIndex": seo.noIndex == true || isDemo == true, "canonicalUrl": seo.canonicalUrl, "image": seo.image {alt, caption, credit, crop, hotspot, asset->{_id, url, metadata{lqip, dimensions}}}}}': SITE_SETTINGS_QUERY_RESULT;
    '*[_id == "homepage" && ($includeDemo == true || isDemo != true)][0]{_id,title,heroTitle,heroSubtitle,heroDescription,heroImage {alt, caption, credit, crop, hotspot, asset->{_id, url, metadata{lqip, dimensions}}},heroActions[]{_key,label,href},featuredAreas[]{_key,"area": @-> {_id,title,"slug":slug.current,summary,isDemo,mainImage {alt, caption, credit, crop, hotspot, asset->{_id, url, metadata{lqip, dimensions}}}}}[defined(area) && ($includeDemo == true || area.isDemo != true)],featuredVideos[]{_key,"video": @->{_id,title,"slug":slug.current,youtubeUrl,isDemo,thumbnail {alt, caption, credit, crop, hotspot, asset->{_id, url, metadata{lqip, dimensions}}}}}[defined(video) && ($includeDemo == true || video.isDemo != true)],featuredArticles[]{_key,"article": @->{_id,title,"slug":slug.current,excerpt,isDemo}}[defined(article) && ($includeDemo == true || article.isDemo != true)],contactHeading,contactAction{label,href},isDemo,"seo": {"title": coalesce(seo.title, title), "description": coalesce(seo.description, summary, excerpt, heroDescription, ""), "noIndex": seo.noIndex == true || isDemo == true, "canonicalUrl": seo.canonicalUrl, "image": seo.image {alt, caption, credit, crop, hotspot, asset->{_id, url, metadata{lqip, dimensions}}}}}': HOMEPAGE_QUERY_RESULT;
    '*[_type == "area" && defined(slug.current) && ($includeDemo == true || isDemo != true)] | order(sortOrder asc, title asc)[0...100]{_id,title,"slug":slug.current,summary,mainImage {alt, caption, credit, crop, hotspot, asset->{_id, url, metadata{lqip, dimensions}}},housingTypes,highlights,isDemo,"seo": {"title": coalesce(seo.title, title), "description": coalesce(seo.description, summary, excerpt, heroDescription, ""), "noIndex": seo.noIndex == true || isDemo == true, "canonicalUrl": seo.canonicalUrl, "image": seo.image {alt, caption, credit, crop, hotspot, asset->{_id, url, metadata{lqip, dimensions}}}}}': AREAS_QUERY_RESULT;
    '*[_type == "area" && slug.current == $slug && ($includeDemo == true || isDemo != true)][0]{_id,title,"slug":slug.current,summary,description[]{...,_type == "editorialImage" => {alt, caption, credit, crop, hotspot, asset->{_id, url, metadata{lqip, dimensions}}}},mainImage {alt, caption, credit, crop, hotspot, asset->{_id, url, metadata{lqip, dimensions}}},gallery[]{_key,...,asset->{_id,url,metadata{lqip,dimensions}}},housingTypes,highlights,location,contactAction{label,href},relatedVideos[]{_key,"video": @->{_id,title,youtubeUrl,isDemo}}[defined(video) && ($includeDemo == true || video.isDemo != true)],isDemo,"seo": {"title": coalesce(seo.title, title), "description": coalesce(seo.description, summary, excerpt, heroDescription, ""), "noIndex": seo.noIndex == true || isDemo == true, "canonicalUrl": seo.canonicalUrl, "image": seo.image {alt, caption, credit, crop, hotspot, asset->{_id, url, metadata{lqip, dimensions}}}}}': AREA_QUERY_RESULT;
    '*[_type == "video" && ($includeDemo == true || isDemo != true)] | order(publishedAt desc, _id asc)[0...100]{_id,title,"slug":slug.current,summary,youtubeUrl,thumbnail {alt, caption, credit, crop, hotspot, asset->{_id, url, metadata{lqip, dimensions}}},publishedAt,areas[]{_key,"area": @->{_id,title,"slug":slug.current,isDemo}}[defined(area) && ($includeDemo == true || area.isDemo != true)],isDemo,"seo": {"title": coalesce(seo.title, title), "description": coalesce(seo.description, summary, excerpt, heroDescription, ""), "noIndex": seo.noIndex == true || isDemo == true, "canonicalUrl": seo.canonicalUrl, "image": seo.image {alt, caption, credit, crop, hotspot, asset->{_id, url, metadata{lqip, dimensions}}}}}': VIDEOS_QUERY_RESULT;
    '*[_type == "article" && ($includeDemo == true || isDemo != true)] | order(publishedAt desc, _id asc)[0...100]{_id,title,"slug":slug.current,excerpt,publishedAt,mainImage {alt, caption, credit, crop, hotspot, asset->{_id, url, metadata{lqip, dimensions}}},isDemo,"seo": {"title": coalesce(seo.title, title), "description": coalesce(seo.description, summary, excerpt, heroDescription, ""), "noIndex": seo.noIndex == true || isDemo == true, "canonicalUrl": seo.canonicalUrl, "image": seo.image {alt, caption, credit, crop, hotspot, asset->{_id, url, metadata{lqip, dimensions}}}}}': ARTICLES_QUERY_RESULT;
    '*[_type == "article" && slug.current == $slug && ($includeDemo == true || isDemo != true)][0]{_id,title,"slug":slug.current,excerpt,body[]{...,_type == "editorialImage" => {alt, caption, credit, crop, hotspot, asset->{_id, url, metadata{lqip, dimensions}}}},authorName,publishedAt,mainImage {alt, caption, credit, crop, hotspot, asset->{_id, url, metadata{lqip, dimensions}}},areas[]{_key,"area": @->{_id,title,"slug":slug.current,isDemo}}[defined(area) && ($includeDemo == true || area.isDemo != true)],isDemo,"seo": {"title": coalesce(seo.title, title), "description": coalesce(seo.description, summary, excerpt, heroDescription, ""), "noIndex": seo.noIndex == true || isDemo == true, "canonicalUrl": seo.canonicalUrl, "image": seo.image {alt, caption, credit, crop, hotspot, asset->{_id, url, metadata{lqip, dimensions}}}}}': ARTICLE_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
