import {defineQuery} from 'groq'
const image = `{alt, caption, credit, crop, hotspot, asset->{_id, url, metadata{lqip, dimensions}}}`
const seo = `"seo": {"title": coalesce(seo.title, title), "description": coalesce(seo.description, summary, excerpt, heroDescription, ""), "noIndex": seo.noIndex == true || isDemo == true, "canonicalUrl": seo.canonicalUrl, "image": seo.image ${image}}`
export const SITE_SETTINGS_QUERY = defineQuery(`*[_id == "siteSettings" && ($includeDemo == true || isDemo != true)][0]{_id,title,tagline,agentName,phone,email,whatsappUrl,siteUrl,logo ${image},navigation[]{_key,label,href},socialLinks[]{_key,label,href},footerText,isDemo,${seo}}`)
export const HOMEPAGE_QUERY = defineQuery(`*[_id == "homepage" && ($includeDemo == true || isDemo != true)][0]{_id,title,heroTitle,heroSubtitle,heroDescription,heroImage ${image},heroActions[]{_key,label,href},featuredAreas[]{_key,"area": @-> {_id,title,"slug":slug.current,summary,isDemo,mainImage ${image}}}[defined(area) && ($includeDemo == true || area.isDemo != true)],featuredVideos[]{_key,"video": @->{_id,title,"slug":slug.current,youtubeUrl,isDemo,thumbnail ${image}}}[defined(video) && ($includeDemo == true || video.isDemo != true)],featuredArticles[]{_key,"article": @->{_id,title,"slug":slug.current,excerpt,isDemo}}[defined(article) && ($includeDemo == true || article.isDemo != true)],contactHeading,contactAction{label,href},isDemo,${seo}}`)
export const AREAS_QUERY = defineQuery(`*[_type == "area" && defined(slug.current) && ($includeDemo == true || isDemo != true)] | order(sortOrder asc, title asc)[0...100]{_id,title,"slug":slug.current,summary,mainImage ${image},housingTypes,highlights,isDemo,${seo}}`)
export const AREA_QUERY = defineQuery(`*[_type == "area" && slug.current == $slug && ($includeDemo == true || isDemo != true)][0]{_id,title,"slug":slug.current,summary,description[]{...,_type == "editorialImage" => ${image}},mainImage ${image},gallery[]{_key,...,${"asset->{_id,url,metadata{lqip,dimensions}}"}},housingTypes,highlights,location,contactAction{label,href},relatedVideos[]{_key,"video": @->{_id,title,youtubeUrl,isDemo}}[defined(video) && ($includeDemo == true || video.isDemo != true)],isDemo,${seo}}`)
export const VIDEOS_QUERY = defineQuery(`*[_type == "video" && ($includeDemo == true || isDemo != true)] | order(publishedAt desc, _id asc)[0...100]{_id,title,"slug":slug.current,summary,youtubeUrl,thumbnail ${image},publishedAt,areas[]{_key,"area": @->{_id,title,"slug":slug.current,isDemo}}[defined(area) && ($includeDemo == true || area.isDemo != true)],isDemo,${seo}}`)
export const ARTICLES_QUERY = defineQuery(`*[_type == "article" && ($includeDemo == true || isDemo != true)] | order(publishedAt desc, _id asc)[0...100]{_id,title,"slug":slug.current,excerpt,publishedAt,mainImage ${image},isDemo,${seo}}`)
export const ARTICLE_QUERY = defineQuery(`*[_type == "article" && slug.current == $slug && ($includeDemo == true || isDemo != true)][0]{_id,title,"slug":slug.current,excerpt,body[]{...,_type == "editorialImage" => ${image}},authorName,publishedAt,mainImage ${image},areas[]{_key,"area": @->{_id,title,"slug":slug.current,isDemo}}[defined(area) && ($includeDemo == true || area.isDemo != true)],isDemo,${seo}}`)
